### ISSUE TITLE
Cron Time in Docker Compose Example Is Incorrect

### ISSUE THREAD

**Issue by kramttocs** [jmqm/vaultwarden_backup#32]
The example value is:

- CRON_TIME=* */24 * * * # Runs at 12:00 AM.

This is actually: At every minute past every 24th hour
So you end up with 60 backups per day

Should be:

 - CRON_TIME=0 0 * * * # Runs at 12:00 AM.

**Comment by jmqm** [comment]
Thank you 😄 

![hellinheavns-capybara](https://github.com/user-attachments/assets/d7a1de08-1016-4886-bdb9-398785dc2364)

**Comment by kramttocs** [comment]
I really appreciate you making this available. Works slick!
